# Generated by Django 5.1.15 on 2026-03-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('strict', 'Strict'), ('balanced', 'Balanced'), ('custom', 'Custom')], default='balanced', max_length=20)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='ps_core.site')),
            ],
        ),
    ]
