# Generated by Django 5.1.15 on 2026-03-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0002_sitepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='reasons_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scansession',
            name='recommendations_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
